"""initial schema

Revision ID: 1ebc143dc9ec
Revises: 
Create Date: 2026-05-28 17:18:54.100286

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1ebc143dc9ec'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('credits_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules'))
    )
    op.create_index(op.f('ix_pricing_rules_resource_type'), 'pricing_rules', ['resource_type'], unique=True)
    op.create_table('users',
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('credits_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    op.create_table('communities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vk_group_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('group_avatar', sa.String(), nullable=True),
    sa.Column('access_token_encrypted', sa.String(), nullable=False),
    sa.Column('token_permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('callback_server_id', sa.Integer(), nullable=True),
    sa.Column('callback_confirm_code', sa.String(length=20), nullable=True),
    sa.Column('callback_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_communities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communities')),
    sa.UniqueConstraint('user_id', 'vk_group_id', name=op.f('uq_communities_user_id'))
    )
    op.create_index(op.f('ix_communities_user_id'), 'communities', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions'))
    )
    op.create_index('ix_credit_tx_user_date', 'credit_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('ai_agents',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('confidence_threshold', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('fallback_action', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_ai_agents_community_id_communities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_agents'))
    )
    op.create_index(op.f('ix_ai_agents_community_id'), 'ai_agents', ['community_id'], unique=False)
    op.create_table('bot_flows',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_value', sa.Text(), nullable=True),
    sa.Column('flow_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_bot_flows_community_id_communities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_flows'))
    )
    op.create_index(op.f('ix_bot_flows_community_id'), 'bot_flows', ['community_id'], unique=False)
    op.create_table('content_posts',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vk_post_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_content_posts_community_id_communities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_posts'))
    )
    op.create_index(op.f('ix_content_posts_community_id'), 'content_posts', ['community_id'], unique=False)
    op.create_index(op.f('ix_content_posts_scheduled_at'), 'content_posts', ['scheduled_at'], unique=False)
    op.create_table('mailings',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segment_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_mailings_community_id_communities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailings'))
    )
    op.create_index(op.f('ix_mailings_community_id'), 'mailings', ['community_id'], unique=False)
    op.create_index('ix_mailings_status_scheduled', 'mailings', ['status', 'scheduled_at'], unique=False)
    op.create_table('subscribers',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('can_message', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_subscribers_community_id_communities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscribers')),
    sa.UniqueConstraint('community_id', 'vk_user_id', name=op.f('uq_subscribers_community_id'))
    )
    op.create_index(op.f('ix_subscribers_community_id'), 'subscribers', ['community_id'], unique=False)
    op.create_index(op.f('ix_subscribers_vk_user_id'), 'subscribers', ['vk_user_id'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('credits_spent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], name=op.f('fk_agent_conversations_agent_id_ai_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_agent_conversations_subscriber_id_subscribers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_conversations'))
    )
    op.create_index(op.f('ix_agent_conversations_agent_id'), 'agent_conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_subscriber_id'), 'agent_conversations', ['subscriber_id'], unique=False)
    op.create_table('bot_states',
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('current_node_id', sa.String(length=100), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['bot_flows.id'], name=op.f('fk_bot_states_flow_id_bot_flows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_bot_states_subscriber_id_subscribers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_states')),
    sa.UniqueConstraint('flow_id', 'subscriber_id', name=op.f('uq_bot_states_flow_id'))
    )
    op.create_index(op.f('ix_bot_states_flow_id'), 'bot_states', ['flow_id'], unique=False)
    op.create_index(op.f('ix_bot_states_subscriber_id'), 'bot_states', ['subscriber_id'], unique=False)
    op.create_table('knowledge_base_documents',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=True),
    sa.Column('qdrant_collection', sa.String(length=100), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], name=op.f('fk_knowledge_base_documents_agent_id_ai_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_documents'))
    )
    op.create_index(op.f('ix_knowledge_base_documents_agent_id'), 'knowledge_base_documents', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_documents_agent_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    op.drop_index(op.f('ix_bot_states_subscriber_id'), table_name='bot_states')
    op.drop_index(op.f('ix_bot_states_flow_id'), table_name='bot_states')
    op.drop_table('bot_states')
    op.drop_index(op.f('ix_agent_conversations_subscriber_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_agent_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index(op.f('ix_subscribers_vk_user_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_community_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index('ix_mailings_status_scheduled', table_name='mailings')
    op.drop_index(op.f('ix_mailings_community_id'), table_name='mailings')
    op.drop_table('mailings')
    op.drop_index(op.f('ix_content_posts_scheduled_at'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_community_id'), table_name='content_posts')
    op.drop_table('content_posts')
    op.drop_index(op.f('ix_bot_flows_community_id'), table_name='bot_flows')
    op.drop_table('bot_flows')
    op.drop_index(op.f('ix_ai_agents_community_id'), table_name='ai_agents')
    op.drop_table('ai_agents')
    op.drop_index('ix_credit_tx_user_date', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_communities_user_id'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pricing_rules_resource_type'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###