"""agent_conversations subscriber_id nullable

Revision ID: 89f2a66f5a0c
Revises: 1ebc143dc9ec
Create Date: 2026-05-28 18:18:36.633546

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '89f2a66f5a0c'
down_revision: str | None = '1ebc143dc9ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_conversations', 'subscriber_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_conversations', 'subscriber_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###